"use client";

import { create } from "zustand";
import type {
  Conversation,
  ContextWarningEvent,
  Message,
  ModelInfo,
  ModelSwitchEvent,
} from "@synq/shared-types";

type StreamingState = "idle" | "sending" | "streaming" | "error";

interface ChatState {
  conversations: Conversation[];
  currentConversationId: string | null;
  /** Per-conversation current_model — the active selection in the picker. */
  currentModel: string | null;
  /** All registered models, fetched once from GET /models. */
  models: ModelInfo[];
  defaultModel: string | null;
  messages: Message[];
  /** Token buffer for the in-flight assistant turn; cleared when `done` arrives. */
  streamingText: string;
  /** Optimistic user message rendered before the server confirms. */
  pendingUserText: string | null;
  streamingState: StreamingState;
  errorMessage: string | null;
  /** Banner: "Earlier messages dropped to fit context". */
  contextWarning: ContextWarningEvent | null;
  /** Badge: "Switched to <provider>". Carries the model id for display. */
  lastSwitch: ModelSwitchEvent | null;
  /**
   * Assistant turn IDs where the streamed reply was generated by a
   * different model from the prior assistant turn. Used to render the
   * per-message "Switched to X" badge on render.
   */
  switchedTurnIds: Record<string, true>;

  setConversations: (rows: Conversation[]) => void;
  setCurrentConversation: (id: string | null) => void;
  setCurrentModel: (model: string | null) => void;
  setModels: (models: ModelInfo[], defaultModel: string) => void;
  setMessages: (rows: Message[]) => void;
  prependConversation: (c: Conversation) => void;

  beginSend: (text: string) => void;
  appendStreamToken: (text: string) => void;
  reconcileUserMessage: (m: Message) => void;
  applyModelSwitch: (e: ModelSwitchEvent) => void;
  applyContextWarning: (e: ContextWarningEvent) => void;
  completeAssistant: (m: Message) => void;
  failStream: (msg: string) => void;
}

export const useChatStore = create<ChatState>((set) => ({
  conversations: [],
  currentConversationId: null,
  currentModel: null,
  models: [],
  defaultModel: null,
  messages: [],
  streamingText: "",
  pendingUserText: null,
  streamingState: "idle",
  errorMessage: null,
  contextWarning: null,
  lastSwitch: null,
  switchedTurnIds: {},

  setConversations: (rows) => set({ conversations: rows }),
  setCurrentConversation: (id) =>
    set({
      currentConversationId: id,
      messages: [],
      streamingText: "",
      pendingUserText: null,
      streamingState: "idle",
      errorMessage: null,
      contextWarning: null,
      lastSwitch: null,
      switchedTurnIds: {},
    }),
  setCurrentModel: (model) => set({ currentModel: model }),
  setModels: (models, defaultModel) => set({ models, defaultModel }),
  setMessages: (rows) =>
    set(() => ({
      messages: rows,
      // Recompute switched-turn highlights from history. Each assistant
      // turn whose model_used differs from the previous assistant's is
      // tagged for the badge.
      switchedTurnIds: deriveSwitchedTurnIds(rows),
    })),
  prependConversation: (c) =>
    set((s) => ({ conversations: [c, ...s.conversations] })),

  beginSend: (text) =>
    set({
      pendingUserText: text,
      streamingText: "",
      streamingState: "sending",
      errorMessage: null,
      contextWarning: null,
      lastSwitch: null,
    }),

  appendStreamToken: (text) =>
    set((s) => ({
      streamingText: s.streamingText + text,
      streamingState: "streaming",
    })),

  reconcileUserMessage: (m) =>
    set((s) => ({
      messages: [...s.messages, m],
      pendingUserText: null,
    })),

  applyModelSwitch: (e) => set({ lastSwitch: e }),
  applyContextWarning: (e) => set({ contextWarning: e }),

  completeAssistant: (m) =>
    set((s) => {
      const switchedTurnIds = { ...s.switchedTurnIds };
      // Tag the new assistant turn if either (a) the orchestrator
      // flagged a drift event, or (b) its model_used differs from the
      // previous assistant turn.
      const priorAssistant = [...s.messages]
        .reverse()
        .find((x) => x.role === "assistant");
      if (
        s.lastSwitch ||
        (m.model_used &&
          priorAssistant?.model_used &&
          m.model_used !== priorAssistant.model_used)
      ) {
        switchedTurnIds[m.id] = true;
      }
      return {
        messages: [...s.messages, m],
        streamingText: "",
        streamingState: "idle",
        switchedTurnIds,
        currentModel: m.model_used ?? s.currentModel,
      };
    }),

  failStream: (msg) =>
    set({
      streamingState: "error",
      errorMessage: msg,
      streamingText: "",
      pendingUserText: null,
    }),
}));

function deriveSwitchedTurnIds(messages: Message[]): Record<string, true> {
  const out: Record<string, true> = {};
  let lastAssistantModel: string | null = null;
  for (const m of messages) {
    if (m.role !== "assistant") continue;
    if (
      lastAssistantModel &&
      m.model_used &&
      m.model_used !== lastAssistantModel
    ) {
      out[m.id] = true;
    }
    if (m.model_used) lastAssistantModel = m.model_used;
  }
  return out;
}
