"""Shared `resolve_file` logic used by every adapter.

The decision tree is identical across providers — only the capability
flags differ. Each adapter declares its `ProviderCapabilities`; this
helper applies the Phase 3 rules:

    image + vision-capable + small enough -> inline bytes
    image + vision-capable + too big + Files API -> Files API URI
    image + non-vision                  -> description / OCR text
    PDF / DOCX / TXT / MD               -> extracted_text
    failed parse                        -> "[file unavailable: ...]"

Gemini overrides the inline branch to upload via the Files API instead.
Everything else uses the default path defined here.
"""

from __future__ import annotations

import logging
from typing import Any

from app.adapters.base import ProviderCapabilities, ResolvedFile
from app.storage import download_bytes, key_from_storage_url

logger = logging.getLogger(__name__)


_IMAGE_MIMES = {"image/png", "image/jpeg", "image/jpg", "image/webp"}


def is_image(mime: str | None) -> bool:
    return (mime or "").lower() in _IMAGE_MIMES


def _description_text(file_row: Any) -> str:
    """Best-available text snapshot of a file for a non-vision target.

    Combines OCR text (when present) with the vision-model description.
    The two are kept distinct (description != extracted_text) so OCR
    failures still leave the description available.
    """
    extracted = (file_row.extracted_text or "").strip()
    description = (file_row.description or "").strip()
    if extracted and description:
        return (
            f"[Description of attached image]\n{description}\n\n"
            f"[Text recognized in image]\n{extracted}"
        )
    if description:
        return f"[Description of attached image]\n{description}"
    if extracted:
        return f"[Text extracted from attached file]\n{extracted}"
    return ""


def default_resolve(
    file_row: Any,
    *,
    capabilities: ProviderCapabilities,
) -> ResolvedFile:
    """Phase 3 baseline resolver used by every non-Gemini adapter."""
    file_id = str(file_row.id)
    mime = file_row.mime_type

    if file_row.parse_status == "failed":
        return ResolvedFile(
            file_id=file_id,
            mime_type=mime,
            description_text=f"[file unavailable: {(file_row.error or {}).get('message','parse_failed')}]",
            strategy="description",
            note="parse_failed",
        )

    if is_image(mime):
        max_bytes = capabilities.max_image_mb * 1024 * 1024
        fits_inline = (
            capabilities.vision
            and capabilities.max_image_mb > 0
            and (file_row.size_bytes or 0) <= max_bytes
        )
        if fits_inline:
            try:
                raw = download_bytes(key_from_storage_url(file_row.storage_url))
            except Exception:
                logger.exception("resolve_file: S3 download failed for %s", file_id)
                # Degrade to description rather than fail the whole turn.
                return ResolvedFile(
                    file_id=file_id,
                    mime_type=mime,
                    description_text=_description_text(file_row),
                    strategy="description",
                    note="s3_unavailable",
                )
            return ResolvedFile(
                file_id=file_id,
                mime_type=mime,
                inline_bytes=raw,
                strategy="inline",
            )
        # Non-vision target OR image too big — substitute description.
        desc = _description_text(file_row)
        if not desc:
            name = getattr(file_row, "original_filename", None) or file_id
            desc = (
                f"[Image '{name}' was attached. A text description is being "
                f"generated by the pipeline — it will be available once "
                f"parse_status changes from '{file_row.parse_status}' to 'done'.]"
            )
        return ResolvedFile(
            file_id=file_id,
            mime_type=mime,
            description_text=desc,
            strategy="description",
            note="non_vision" if not capabilities.vision else "size_exceeds_inline",
        )

    # Non-image files (PDF / DOCX / TXT / MD) — always substitute
    # extracted text. RAG chunk selection arrives in Phase 4.
    extracted = (file_row.extracted_text or "").strip()
    if not extracted:
        return ResolvedFile(
            file_id=file_id,
            mime_type=mime,
            description_text=f"[file '{file_row.original_filename or file_id}' attached, no text extracted yet]",
            strategy="description",
            note="no_extracted_text",
        )
    return ResolvedFile(
        file_id=file_id,
        mime_type=mime,
        description_text=(
            f"[Contents of attached file '{file_row.original_filename or file_id}']\n"
            f"{extracted}"
        ),
        strategy="description",
    )
