"""Turn orchestrator — provider-agnostic.

This module owns the turn lifecycle described in SYNQ_STRUCT §"Tier 4 —
Orchestrator":

    validate -> build context -> call provider -> stream -> persist

CRITICAL CONSTRAINT (per Phase 2 spec):
    NO provider-specific conditionals live here. The only thing this
    module knows is "give me an adapter for this model id, then call the
    protocol methods." If a future change requires `if provider ==
    "anthropic"` here, that branch belongs in an adapter instead.

Phase 2 capabilities:
  * Naive truncation when the prompt exceeds `target_window * 0.75`
    (drops oldest non-system turns first; logs a warning; emits a
    `context_warning` SSE event so the UI can show "Earlier messages
    dropped"). Phase 4 replaces this with the six-part compression
    assembly.
  * Identity-drift handling: when the conversation's previous assistant
    turn was generated by a different model, a small system note is
    prepended ("Continuing this conversation. Earlier responses were
    from a different model.").
"""

from __future__ import annotations

import logging
from collections.abc import AsyncIterator
from dataclasses import dataclass
from typing import Any

from app.adapters import ProviderAdapter, adapter_for, provider_for
from app.adapters.base import StreamEvent
from app.models import Message, TextBlock

logger = logging.getLogger(__name__)


_TRUNCATION_RATIO = 0.75  # Trigger truncation at 75% of the context window.
_IDENTITY_DRIFT_NOTE = (
    "Continuing this conversation. Earlier responses were from a different model. "
    "Refer to the previous discussion as 'the previous conversation', not as your "
    "own prior statements."
)


@dataclass
class TurnPlan:
    """The complete plan for a single assistant turn.

    Built by `plan_turn`. Held as a value object so the replay tool can
    inspect it without running the network call.
    """

    adapter: ProviderAdapter
    provider: str
    model: str
    messages: list[Message]  # post-truncation, post-drift-note
    wire_request: dict[str, Any]
    truncated: bool
    dropped_count: int
    drift_detected: bool
    prompt_token_estimate: int
    context_window: int


async def plan_turn(
    history: list[Message],
    target_model: str,
) -> TurnPlan:
    """Assemble the request for `target_model` given canonical history.

    Steps (all provider-agnostic):
      1. Detect identity drift (prior assistant turn used a different
         model) and prepend a system note if so.
      2. Pick an adapter for `target_model` and count tokens.
      3. If tokens > window * 0.75, drop oldest non-system turns until
         it fits. (Phase 4 will replace this with smart compression.)
      4. Call `adapter.translate_messages(...)` to get the wire payload.
    """
    adapter = adapter_for(target_model)

    # Identity-drift detection — purely based on observed model_used
    # values, not on the provider name. If ANY prior assistant turn was
    # generated by a different model id, we add the system note.
    drift_detected = _detect_drift(history, target_model)
    messages = list(history)
    if drift_detected:
        # Prepend (not append) so the model sees the framing before the
        # conversation. We synthesize a Message with only the fields the
        # adapter touches; tests rely on us not pretending it's a real
        # turn from the DB.
        note = _build_drift_note()
        messages = [note] + messages

    target_window = adapter.context_window
    threshold = int(target_window * _TRUNCATION_RATIO)

    # Fast path: a char-length estimate is enough to know we're nowhere
    # near the window. Skipping the real count_tokens call here means a
    # cold-cache HF tokenizer download never blocks the SSE stream on
    # short conversations.
    char_estimate = _char_estimate(messages)
    if char_estimate < threshold * 2:  # ~8 chars/token safety margin
        prompt_tokens = char_estimate
        truncated = False
        dropped = 0
    else:
        prompt_tokens = await adapter.count_tokens(messages)
        truncated = False
        dropped = 0
        if prompt_tokens > threshold:
            messages, dropped, prompt_tokens = await _truncate_oldest(
                messages, adapter, threshold
            )
            truncated = dropped > 0
            if truncated:
                logger.warning(
                    "context truncation: dropped %d oldest messages for model=%s "
                    "(estimate now %d, threshold %d). Phase 4 will replace this.",
                    dropped,
                    target_model,
                    prompt_tokens,
                    threshold,
                )

    wire_request = await adapter.translate_messages(messages)

    return TurnPlan(
        adapter=adapter,
        provider=adapter.provider,
        model=target_model,
        messages=messages,
        wire_request=wire_request,
        truncated=truncated,
        dropped_count=dropped,
        drift_detected=drift_detected,
        prompt_token_estimate=prompt_tokens,
        context_window=target_window,
    )


async def run_turn(plan: TurnPlan) -> AsyncIterator[StreamEvent]:
    """Execute the planned turn against the chosen provider.

    Yields canonical StreamEvents. Routers consume these and translate
    to SSE — that translation is the only place we touch HTTP shapes.
    """
    validation = await plan.adapter.validate(plan.wire_request)
    if not validation.ok:
        yield StreamEvent(
            type="error",
            content=f"validation_failed: {'; '.join(validation.errors)}",
        )
        return

    async for event in await plan.adapter.stream_completion(plan.wire_request):
        yield event


# ── Helpers ─────────────────────────────────────────────────────────────


def _detect_drift(history: list[Message], target_model: str) -> bool:
    """True when any prior assistant turn was generated by a different model."""
    for m in reversed(history):
        if m.role == "assistant" and m.model_used and m.model_used != target_model:
            return True
        if m.role == "assistant" and m.model_used == target_model:
            return False
    return False


def _build_drift_note() -> Message:
    """A synthetic system Message containing the identity-drift framing."""
    from datetime import datetime, timezone
    from uuid import UUID

    return Message(
        id=UUID("00000000-0000-0000-0000-000000000000"),
        conversation_id=UUID("00000000-0000-0000-0000-000000000000"),
        turn_index=-1,
        role="system",
        content=[TextBlock(text=_IDENTITY_DRIFT_NOTE)],
        model_used=None,
        token_counts=None,
        cost_usd=None,
        embedding_status="pending",
        idempotency_key=None,
        created_at=datetime.now(timezone.utc),
    )


def _char_estimate(messages: list[Message]) -> int:
    """Cheap, sync rough-token-count using char-length / 4.

    Used to short-circuit the real `count_tokens` call on small
    histories so the SSE stream doesn't wait on a cold tokenizer.
    Always conservative (overcounts) — never under-truncates.
    """
    total = 0
    for m in messages:
        for block in m.content:
            if isinstance(block, TextBlock):
                total += len(block.text)
    return total // 4


async def _truncate_oldest(
    messages: list[Message],
    adapter: ProviderAdapter,
    threshold: int,
) -> tuple[list[Message], int, int]:
    """Drop the oldest non-system, non-final messages until under threshold.

    Always preserves: (1) any leading system messages, (2) the final
    user message (the current question). Drops one message per step
    from the start of the body, re-counting tokens via the adapter
    after each drop so the result is honest about how much we shed.

    Returns (kept_messages, dropped_count, final_token_count).
    """
    prefix: list[Message] = []
    body: list[Message] = list(messages)
    while body and body[0].role == "system":
        prefix.append(body.pop(0))

    tail: list[Message] = []
    if body and body[-1].role == "user":
        tail.append(body.pop())

    dropped = 0
    current = prefix + body + tail
    token_count = await adapter.count_tokens(current)
    while body and token_count > threshold:
        body.pop(0)
        dropped += 1
        current = prefix + body + tail
        token_count = await adapter.count_tokens(current)

    return current, dropped, token_count


def provider_for_model(model: str) -> str:
    """Re-export of `adapters.provider_for` for orchestrator callers."""
    return provider_for(model)
